# Nama workflow yang akan tampil di tab Actions GitHub
name: Deploy Aplikasi SIKAP ke VPS

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ main ]

# Daftar pekerjaan yang akan dijalankan
jobs:
  deploy:
    runs-on: ubuntu-latest # Menggunakan server virtual sementara dari GitHub

    steps:
      # 1. Mengambil kode dari repository Anda
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup PHP dengan versi yang benar dan ekstensi yang dibutuhkan
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, dom, zip, gd, mysql
          tools: composer

      # 3. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 4. Install semua dependensi
      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Frontend Assets
        run: npm run build

      # 5. Salin file produksi (termasuk .env) ke server
      - name: Copy production files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "." # Salin semua dari direktori kerja saat ini
          target: "/var/www/sikap"
          strip_components: 1 # Untuk menghindari pembuatan subfolder tambahan

      # 6. Jalankan perintah deployment di server VPS Anda
      - name: Run deployment commands on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/sikap
            sudo php artisan down
            sudo composer install --no-dev --optimize-autoloader
            sudo php artisan migrate --force
            sudo php artisan optimize:clear
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            sudo php artisan up
