name: Deploy SIKAP Application to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Connect and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pindah ke direktori aplikasi
            cd /var/www/sikap

            # Aktifkan maintenance mode (butuh sudo)
            sudo php artisan down

            # Tarik kode terbaru dari branch main (TANPA SUDO)
            git pull origin main

            # Instal dependensi PHP & JS sebagai user biasa
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run build

            # Atur hak akses agar web server bisa menulis (Langkah Paling Penting)
            sudo chown -R www-data:www-data storage bootstrap/cache

            # Jalankan migrasi dan optimasi dengan sudo
            sudo php artisan migrate --force
            sudo php artisan optimize:clear
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache

            # Nonaktifkan maintenance mode
            sudo php artisan up
