# Nama workflow yang akan tampil di tab Actions GitHub
name: Deploy SIKAP Application to VPS

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # Menggunakan server virtual Ubuntu terbaru dari GitHub untuk menjalankan proses
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dieksekusi
    steps:
      # Langkah ini hanya untuk memastikan workflow ini bisa berjalan
      - name: Checkout Code
        uses: actions/checkout@v4

      # Langkah utama: Login ke server dan jalankan semua perintah di sana
      - name: Connect to VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/sikap
            sudo php artisan down
            git pull origin main
            sudo composer install --optimize-autoloader
            sudo npm install && sudo npm run build
            sudo php artisan migrate --force
            sudo php artisan optimize:clear
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            sudo php artisan up
