# Nama workflow yang akan tampil di tab Actions GitHub
name: Deploy Aplikasi SIKAP ke VPS

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode dari repository Anda
      - name: 1. Checkout Code from Repository
        uses: actions/checkout@v4

      # 2. Setup PHP dengan versi yang benar
      - name: 2. Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, dom, zip, gd, mysql
          tools: composer

      # 3. Setup Node.js
      - name: 3. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 4. Install semua dependensi
      - name: 4. Install Application Dependencies
        # PERBAIKAN DI SINI: Flag --no-dev dihapus
        run: |
          composer install --prefer-dist --optimize-autoloader
          npm install
          npm run build

      # 5. Salin file produksi ke server
      - name: 5. Copy production files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/var/www/sikap"
          strip_components: 1

      # 6. Jalankan perintah deployment di server VPS Anda
      - name: 6. Run deployment commands on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/sikap
            sudo php artisan down
            sudo composer install --optimize-autoloader
            sudo php artisan migrate --force
            sudo php artisan optimize:clear
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            sudo php artisan up
