# Nama workflow yang akan tampil di tab Actions GitHub
name: Deploy SIKAP Application to VPS

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # Menggunakan server virtual Ubuntu terbaru dari GitHub untuk menjalankan proses
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dieksekusi
    steps:
      # Langkah ini hanya untuk memastikan workflow ini bisa berjalan
      - name: Checkout Code
        uses: actions/checkout@v4

      # Langkah utama: Login ke server dan jalankan semua perintah di sana
      - name: Connect to VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Pindah ke direktori aplikasi di server
            cd /var/www/sikap

            # 2. Aktifkan maintenance mode
            sudo php artisan down

            # 3. Tarik kode terbaru dari branch main
            sudo git pull origin main

            # 4. Instal dependensi PHP (termasuk dev-dependencies seperti Faker)
            sudo composer install --optimize-autoloader

            # 5. Instal dependensi JS & build aset frontend
            sudo npm install
            sudo npm run build

            # 6. Jalankan migrasi database jika ada perubahan
            sudo php artisan migrate --force

            # 7. Hapus cache lama dan buat cache baru untuk produksi
            sudo php artisan optimize:clear
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache

            # 8. Nonaktifkan maintenance mode, aplikasi kembali online
            sudo php artisan up
